#ping the server

- name: ping the server
  hosts: [frontend]
  tasks:
    - name: ping the server
      ansible.builtin.ping:

    - name: print the hostname
      ansible.builtin.debug:
        msg: "The hostname is {{ inventory_hostname }}"
 
