- name : manjunatha
  hosts: local
  connection: local

  vars:
    course_name: "Ansible"
    duration: "4 weeks"
    trainer: "Manjunatha Kullai"

    tasks:
      - name: Print the course details
        ansible.builtin.debug:
          msg: "This is the {{ course_name }} course by {{ trainer }}. It lasts for {{ duration }}"

      - name: Print the course details with variables
        course_name: "Devops"
        duration: "6 weeks"
        ansible.builtin.debug:
          msg: "This is the {{ course_name }} course by {{ trainer }}. It lasts for {{ duration }}"