- name: reading variable from differnt places
  hosts: local
  connection: local
  vars:
    #COURSE: "Devops and aws"
    #DURATION: "3 months"
    #TRAINER: "Rama"
  vars_files:
    - course.yaml
  vars_prompt:
    - name: "COURSE"
      prompt: "Enter the course name"
      default: "Devops and aws"
    - name: "DURATION"
      prompt: "Enter the course duration"
      default: "3 months"
    - name: "TRAINER"
      prompt: "Enter the trainer's name"
      default: "Rama"
  tasks:
    - name: Print the course name
     # vars:
       # COURSE: "Ansible"
       # TRAINER: "Manjunatha"
        #DURATION: "0.1 months"
      ansible.builtin.debug:
        msg: "Course Name: {{ COURSE }}, duration: {{ DURATION }} Trainer: {{ TRAINER }}"

        #01-command line first or args is first priority
        # #02-vars is second priority
        # #03-vars_files is third priority
        # #04-vars_prompt is fourth priority
        # #05-vars_precedence is last priority
        # #06-inventory is last priority
  